#!/bin/sh

target="$HOME/.local/bin/shoppy"
if [ ! -e $target ]; then
	if command -v termux-setup-storage >/dev/null; then # then we're in termux
		printf "Copying executable to .local/bin ...\n"
		cp shoppy $target
		chmod u+x $target
	else
		target="$HOME/git/dotfiles/bin/.local/bin/"
		printf "Symlinking executable to dotfiles ... \n"
		ln -s "$(dirname $(readlink -f "$0"))/shoppy" $target
	fi
	printf "Done!\n"
else
	printf "Executable already exists!\n"
fi
